### ISSUE TITLE
Panic in State Tree

### ISSUE THREAD

**Issue by pmuetschard** [ben-clayton/gapid#16]
```
panic: reflect: call of reflect.Value.Interface on zero Value
  panic: reflect: call of reflect.Value.Interface on zero Value

goroutine 32228 [running]:
reflect.valueInterface(0x0, 0x0, 0x0, 0xc45ccd3f01, 0xc45ccd3f20, 0xc46e663080)
  /usr/local/google/work/gapid/go/src/reflect/value.go:924 +0x1fa
reflect.Value.Interface(0x0, 0x0, 0x0, 0x0, 0x0)
  /usr/local/google/work/gapid/go/src/reflect/value.go:919 +0x44
github.com/google/gapid/gapis/resolve.StateTreeNode(0x308f3e0, 0xc45e143000, 0xc45eeca380, 0xc45ccd3e01, 0x1f86560, 0xc45eeca380)
  /usr/local/google/work/gapid/src/github.com/google/gapid/gapis/resolve/state_tree.go:140 +0xd43
github.com/google/gapid/gapis/resolve.ResolveInternal(0x308f3e0, 0xc45e143000, 0x3090220, 0xc45eeca380, 0x1cad040, 0xc46e662f48, 0x3090220, 0xc45eeca380)
  /usr/local/google/work/gapid/src/github.com/google/gapid/gapis/resolve/resolve.go:268 +0x556
github.com/google/gapid/gapis/resolve.ResolveService(0x308f3e0, 0xc45e143000, 0x3090220, 0xc45eeca380, 0x1d76800, 0x1e33c40, 0x1, 0x3065ae0)
  /usr/local/google/work/gapid/src/github.com/google/gapid/gapis/resolve/resolve.go:203 +0x4d
github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve(0xc46e662f60, 0x308f3e0, 0xc45e143000, 0x3065ae0, 0xc46e662f60, 0x1, 0x306a2a0)
  /usr/local/google/work/gapid/src/github.com/google/gapid/gapis/resolve/get.go:35 +0xa9
github.com/google/gapid/gapis/database.(*record).resolve(0xc45ee7d950, 0x308f3e0, 0xc45e143000, 0xc45ee84400, 0xc45ee7d5f0)
  /usr/local/google/work/gapid/src/github.com/google/gapid/gapis/database/memory.go:72 +0x8a
github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1(0xc45ee7d950, 0xc45e143040, 0xc42033c140)
  /usr/local/google/work/gapid/src/github.com/google/gapid/gapis/database/memory.go:144 +0x45
created by github.com/google/gapid/gapis/database.(*memory).resolveLocked
  /usr/local/google/work/gapid/src/github.com/google/gapid/gapis/database/memory.go:151 +0x4ff
```

**Comment by ben-clayton** [comment]
Can you please email me a trace that has this issue?

**Comment by pmuetschard** [comment]
Bad news: I can reproduce this panic.
Good news: I know when it happens and have a fix: deref() calls Elem() on nil values which returns a zero value.
