### ISSUE TITLE
Gapit state does not work for Vulkan.

### ISSUE THREAD

**Issue by AWoloszyn** [ben-clayton/gapid#21]
It looks like we cannot correctly unbox slices.
```
root:
    ├── Instances:
    │   └── 3853185920:
    │       ├── ApiVersion: 4194304
    │       ├── EnabledExtensions:
    │       │   ├── 0: VK_KHR_surface
    │       │   └── 1: VK_KHR_android_surface
    │       ├── EnabledLayers:
    │       │   └── 0: VkGraphicsSpy
    │       └── VulkanHandle: 3853185920
    ├── PhysicalDevices:
    │   └── 3547565824:
    │       ├── Instance: 3853185920
    │       ├── Index: 0
    │       ├── MemoryProperties:
    │       │   ├── MemoryTypeCount: 4
    │       │   ├── MemoryTypes:
14:42:59.548 E: <gapis> panic: Unsupported Type []vulkan.VkMemoryType
14:42:59.548 E: <gapis>
14:42:59.548 E: <gapis> goroutine 553 [running]:
14:42:59.548 E: <gapis> github.com/google/gapid/gapis/service/box.(*boxer).val(0xc424dd5760, 0x1c4d280, 0xc4252e6e40, 0x97, 0x97)
14:42:59.548 E: <gapis>         /work/Development/d/src/github.com/google/gapid/gapis/service/box/box.go:170 +0xe74
14:42:59.548 E: <gapis> github.com/google/gapid/gapis/service/box.NewValue(0x1c4d280, 0xc4252e6e40, 0x97)
14:42:59.548 E: <gapis>         /work/Development/d/src/github.com/google/gapid/gapis/service/box/box.go:31 +0xe1
14:42:59.548 E: <gapis> github.com/google/gapid/gapis/resolve.stateValuePreview(0x1ca6f20, 0xc4200f3454, 0x191, 0x20, 0x1ca6f20)
14:42:59.548 E: <gapis>         /work/Development/d/src/github.com/google/gapid/gapis/resolve/state_tree.go:247 +0x25e
14:42:59.548 E: <gapis> github.com/google/gapid/gapis/resolve.StateTreeNode(0x32375a0, 0xc421da9f40, 0xc4252e6b20, 0xc421dcde68, 0x4f1f03, 0x1e4ce20)
14:42:59.548 E: <gapis>         /work/Development/d/src/github.com/google/gapid/gapis/resolve/state_tree.go:219 +0x1a1c
14:42:59.548 E: <gapis> github.com/google/gapid/gapis/resolve.ResolveInternal(0x32375a0, 0xc421da9f40, 0x32383e0, 0xc4252e6b20, 0x1d29a80, 0xc421cdd3c0, 0x32383e0, 0xc4252e6b20)
14:42:59.548 E: <gapis>         /work/Development/d/src/github.com/google/gapid/gapis/resolve/resolve.go:268 +0x539
14:42:59.548 E: <gapis> github.com/google/gapid/gapis/resolve.ResolveService(0x32375a0, 0xc421da9f40, 0x32383e0, 0xc4252e6b20, 0x1df3780, 0x1eb04a0, 0x1, 0x320d9e0)
14:42:59.548 E: <gapis>         /work/Development/d/src/github.com/google/gapid/gapis/resolve/resolve.go:203 +0x4d
14:42:59.548 E: <gapis> github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve(0xc421cdd3c8, 0x32375a0, 0xc421da9f40, 0x320d9e0, 0xc421cdd3c8, 0x1, 0x3212260)
14:42:59.548 E: <gapis>         /work/Development/d/src/github.com/google/gapid/gapis/resolve/get.go:35 +0xa9
14:42:59.548 E: <gapis> github.com/google/gapid/gapis/database.(*record).resolve(0xc425207ec0, 0x32375a0, 0xc421da9f40, 0xc4252da800, 0xc425207ad0)
14:42:59.548 E: <gapis>         /work/Development/d/src/github.com/google/gapid/gapis/database/memory.go:72 +0x8a
14:42:59.548 E: <gapis> github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1(0xc425207ec0, 0xc421da9f80, 0xc420338140)
14:42:59.548 E: <gapis>         /work/Development/d/src/github.com/google/gapid/gapis/database/memory.go:144 +0x45
14:42:59.548 E: <gapis> created by github.com/google/gapid/gapis/database.(*memory).resolveLocked
14:42:59.548 E: <gapis>         /work/Development/d/src/github.com/google/gapid/gapis/database/memory.go:151 +0x4ff
```

**Comment by ben-clayton** [comment]
Fixed in dbfb42ca7.
